server:
  port: 8086

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5433/petclinic_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # Kafka configuration removed for simplified setup
  # Add back when needed: ./start-services.sh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.WeePetClinic: DEBUG
    org.springframework.kafka: DEBUG
