server:
  port: 8087

spring:
  application:
    name: pet-activities-service
  # MongoDB and Kafka configuration removed for simplified setup
  # Add back when needed: ./start-services.sh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.WeePetClinic: DEBUG
    org.springframework.kafka: DEBUG
